### ISSUE TITLE
Pypi and conda release 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_experimental#2]
Does it make sense to release a pip and conda package? That would simplify the use of these tools in other projects like https://github.com/materialdigital/pyiron-workflow-TEMImageSegmentation

**Comment by jan-janssen** [comment]
@liamhuber , @pmrv , @muh-hassani , @niklassiemer and @Ahmed-Aslam any thoughts on this?

**Comment by liamhuber** [comment]
No strong feelings from my end. If we do release it, first please package the notebooks and data into subdirectories instead of having them at the home level. Other than that, if it will make your life easier then go for it!

**Comment by muh-hassani** [comment]
I am certainly in favor of releasing it, as it makes it much easier to use the experimental job types, rather than placing them somewhere exported to the PYTHONPATH.
I think the reordering and some renamings are vital, which if everyone agree to the release, I can do it.

**Comment by jan-janssen** [comment]
The pip package is released and the conda package is currently in review - I hope we get everything setup over the weekend.
